# .github/workflows/build.yml

# configura nome da action
name: CI Next.js App
# configura quando sera ativada
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # ativar manualmente o workflow
  workflow_dispatch:

jobs:
  # versões mais atuais de dependencias e actions
  build-with-latest-all:
    # configura os do container
    runs-on: ubuntu-latest
    
    # # configura diretorio de trabalho
    # defaults:
    #   run:
    #     working-directory: ./

    # configura permições do GITHUB_TOKEN para o deploy no gh_pages
    permissions:
      contents: write
      pages: write
      id-token: write

      # configura restrição de um deploy simultâneo
    concurrency:
      group: "pages"
      cancel-in-progress: true

    # configura passo-a-passo a ser executado
    steps:

        # copia repositorio
      - uses: actions/checkout@v4
        # instala o node
      - uses: actions/setup-node@v4
        with:
          # versão node atualizada para o build no next.js 13
          node-version: 20

      # ### COMO FAZER O CACHE?
      #   # faz o cache do node-modules
      # - name: Cache node_modules
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

        # acessa diretorio clonado
      - name: log diretorio de trabalho
        run: |
          cd ..
          ls -a
          mkdir -p out
          mv * out/
          git reset out/.git
          git reset out/.github
        # renomeia pastas do build do next
      - name: anorcle/next-pages@v1.0
        uses: anorcle/next-pages@v1.0
        with:
          inputDir: '/out'
          outputDir: '/docs'
        # faz o comit e o push no repositorio gh-pages
      - name: Commit and push changes
        run: |
          git -A
          git commit -m 'rebuild by anorcle/next-pages@v1.0'
          git push


# JOB EM CASO DE ATUALIZAÇÃO NODE INCOMPATIVEL
  # # utiliza actions legado em caso de falha no build
  # build-with-legacy-node-18:
  #   # configura os do container
  #   runs-on: ubuntu-latest
    
  #   # aponta para job "necessario"
  #   needs: build-with-latest-all
  #   # condicional de falha do job selecionado
  #   if: failure()

  #   # configura diretorio de trabalho
  #   defaults:
  #     run:
  #       working-directory: hb_github_portfolio
    
  #   # executa passo-a-passo
  #   steps:
  #     # copia repositorio
  #     - uses: actions/checkout@v4
  #     # instala o node
  #     - uses: actions/setup-node@v4
  #       with:
  #         # versão node necessária para o build correto no next.js 13
  #         node-version: '18'
  #     - run: |
  #         npm i
  #         npm run build
  #     - name: Next Pages
  #       uses: anorcle/next-pages@v1.0
  #     - name: Commit and push changes - Deploy gh-page
  #       run: |
  #         git config --global user.name ${{ secrets.USER_NAME }}
  #         git config --global user.email ${{ secrets.EMAIL }}
  #         cd hb_github_portfolio
  #         git add out/*
  #         git commit -m "New Build"
  #         git remote set-url origin git@github.com:HelberBrito/HelberBrito.github.io.git
  #         git push -f        